tests: Only test help.1

diff --git a/3.2/test/run b/3.2/test/run
--- a/3.2/test/run
+++ b/3.2/test/run
@@ -222,19 +222,16 @@ run_doc_test() {
   local tmpdir=$(mktemp -d)
   local f
   echo "  Testing documentation in the container image"
-  # Extract the help files from the container
-  for f in /usr/share/container-scripts/redis/README.md help.1 ; do
-    docker run --rm ${IMAGE_NAME} /bin/bash -c "cat /${f}" >${tmpdir}/$(basename ${f})
-    # Check whether the files include some important information
-    for term in 6379 REDIS_PASSWORD volume ; do
-      if ! cat ${tmpdir}/$(basename ${f}) | nroff | grep -q -e "${term}" ; then
-        # Pipe the content through nroff to allow for safer grepping
-        echo "ERROR: File /${f} does not include '${term}'."
-        return 1
-      fi
-    done
+  # Extract the help.1 file from the container
+  docker run --rm ${IMAGE_NAME} /bin/bash -c "cat /help.1" >${tmpdir}/help.1
+  # Check whether the help.1 file includes some important information
+  for term in 6379 "REDIS\_PASSWORD" volume; do
+    if ! cat ${tmpdir}/help.1 | grep -F -q -e "${term}" ; then
+      echo "ERROR: File /help.1 does not include '${term}'."
+      return 1
+    fi
   done
-  # Check whether the files use the correct format
+  # Check whether the file uses the correct format
   if ! file ${tmpdir}/help.1 | grep -q roff ; then
     echo "ERROR: /help.1 is not in troff or groff format"
     return 1
